spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DBMS_CONNECTION:jdbc:mysql://${DBMS_IP_CONNECT:localhost}:3306/identify}
    username: {DBMS_USERNAME:root}
    password: {DBMS_PASSWORD:root}
  jpa:
    data-platform: org.hibernate.dialect.MYSQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      transaction:
        jta:
          platform: true
    show-sql: true

jwt:
  signerKey: ${SIGNER_KEY:4neUK67c8/yWzeUvvxM83RqiO+fAz9sd3y+ECdfot/h50UOhfzDgqt9HoGumHN6p}
  valid-token-duration: 600 # second
  refreshable-token-duration: 7200 # second

