server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: App
  profiles:
    active: dev

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer